### ISSUE TITLE
Asphalt Buff not working

### ISSUE THREAD

**Issue by alexbyrd2** [TheWalkingZed/TWZ-Issue-Tracker#2] opened 2022-01-26 14:44 UTC
Not seeing asphalt buff in 7d2d. This is on SH
![image](https://user-images.githubusercontent.com/88847116/151184363-036f066f-9770-4e19-957b-51d84adfd522.png)

**Comment by JamesBridgeford** [comment] 2022-01-26 15:41
duplicate of #7

**Closed by JamesBridgeford** 2022-01-26 15:41 UTC
Labels: bug, help wanted
